//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "example_sea_orm_with_relation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub example_id: Uuid,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::example_sea_orm::Entity",
        from = "Column::ExampleId",
        to = "super::example_sea_orm::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ExampleSeaOrm,
}

impl Related<super::example_sea_orm::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExampleSeaOrm.def()
    }
}

impl Related<super::example_many_to_many::Entity> for Entity {
    fn to() -> RelationDef {
        super::example_sea_orm_with_relation_example_many_to_many::Relation::ExampleManyToMany.def()
    }

    fn via() -> Option<RelationDef> {
        Some(super::example_sea_orm_with_relation_example_many_to_many::Relation::ExampleSeaOrmWithRelation.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
