//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "example_sea_orm")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "custom(\"citext\")")]
    pub name: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::example_sea_orm_with_relation::Entity")]
    ExampleSeaOrmWithRelation,
}

impl Related<super::example_sea_orm_with_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExampleSeaOrmWithRelation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
