//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::example_sea_orm::Entity as ExampleSeaOrm;
pub use super::example_sea_orm::Model as ExampleSeaOrmModel;
pub use super::example_sea_orm::ActiveModel as ExampleActiveModel;
